// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grey': string;
  'red': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
